//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotoApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be 0.
        /// </summary>
        public static string CannotBeZero {
            get {
                return ResourceManager.GetString("CannotBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string CardDownload {
            get {
                return ResourceManager.GetString("CardDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string CardOtherSettings {
            get {
                return ResourceManager.GetString("CardOtherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string CardProfile {
            get {
                return ResourceManager.GetString("CardProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path structure.
        /// </summary>
        public static string CardStorage {
            get {
                return ResourceManager.GetString("CardStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s new?.
        /// </summary>
        public static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixes.
        /// </summary>
        public static string Changelog_Fixes {
            get {
                return ResourceManager.GetString("Changelog_Fixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fix localization
        ///fix UI layout
        ///keep 50 recent log files
        ///validation of profile when loading
        ///allow only one instance of app
        ///fixed crash when using in app update feature.
        /// </summary>
        public static string Changelog_Fixes_List {
            get {
                return ResourceManager.GetString("Changelog_Fixes_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New features.
        /// </summary>
        public static string Changelog_NewFeatures {
            get {
                return ResourceManager.GetString("Changelog_NewFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use embedded thumbnails for thumbnail generation(up to 2x faster generation, uses 6x less memory)
        ///option to use different language for tags (month and day names)
        ///show change log after update
        ///you can see change log and app data from the About dialog
        ///you can now use save as option to update profile settings
        ///auto select first connected device.
        /// </summary>
        public static string Changelog_NewFeatures_List {
            get {
                return ResourceManager.GetString("Changelog_NewFeatures_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string CheckUpdates {
            get {
                return ResourceManager.GetString("CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark mode.
        /// </summary>
        public static string DarkMode {
            get {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start date cannot be greater than the end date.
        /// </summary>
        public static string DateRange_StartGreater {
            get {
                return ResourceManager.GetString("DateRange_StartGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string DateRangeFrom {
            get {
                return ResourceManager.GetString("DateRangeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string DateRangeTo {
            get {
                return ResourceManager.GetString("DateRangeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete profile [{0}]?.
        /// </summary>
        public static string DeleteProfilePrompt {
            get {
                return ResourceManager.GetString("DeleteProfilePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying files.
        /// </summary>
        public static string DeviceCopyingFiles {
            get {
                return ResourceManager.GetString("DeviceCopyingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting file {0}.
        /// </summary>
        public static string DeviceDeletingFile {
            get {
                return ResourceManager.GetString("DeviceDeletingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting downloaded files from device.
        /// </summary>
        public static string DeviceDeletingFilesTask {
            get {
                return ResourceManager.GetString("DeviceDeletingFilesTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted {0}/{1} files.
        /// </summary>
        public static string DeviceDeletingProgress {
            get {
                return ResourceManager.GetString("DeviceDeletingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0}.
        /// </summary>
        public static string DeviceDownloadingFile {
            get {
                return ResourceManager.GetString("DeviceDownloadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering files by date.
        /// </summary>
        public static string DeviceFileFilterDate {
            get {
                return ResourceManager.GetString("DeviceFileFilterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed {0}/{1} files.
        /// </summary>
        public static string DeviceFilesDoneCount {
            get {
                return ResourceManager.GetString("DeviceFilesDoneCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} files.
        /// </summary>
        public static string DeviceFilesFound {
            get {
                return ResourceManager.GetString("DeviceFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating thumbnail {0}.
        /// </summary>
        public static string DeviceGeneratingThumbnail {
            get {
                return ResourceManager.GetString("DeviceGeneratingThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device name.
        /// </summary>
        public static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a device name.
        /// </summary>
        public static string DeviceNameEmpty {
            get {
                return ResourceManager.GetString("DeviceNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting file {0}.
        /// </summary>
        public static string DeviceSortingFile {
            get {
                return ResourceManager.GetString("DeviceSortingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string DeviceState {
            get {
                return ResourceManager.GetString("DeviceState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect.
        /// </summary>
        public static string DeviceStatus_CannotConnect {
            get {
                return ResourceManager.GetString("DeviceStatus_CannotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string DeviceStatus_Ready {
            get {
                return ResourceManager.GetString("DeviceStatus_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string DeviceStatus_Unknown {
            get {
                return ResourceManager.GetString("DeviceStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download files by date.
        /// </summary>
        public static string DownloadDateRange {
            get {
                return ResourceManager.GetString("DownloadDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete downloaded files from device.
        /// </summary>
        public static string DownloadDeleteFile {
            get {
                return ResourceManager.GetString("DownloadDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check files.
        /// </summary>
        public static string DownloadFileCheck {
            get {
                return ResourceManager.GetString("DownloadFileCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download files.
        /// </summary>
        public static string DownloadFiles {
            get {
                return ResourceManager.GetString("DownloadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download new files since last backup.
        /// </summary>
        public static string DownloadNewFiles {
            get {
                return ResourceManager.GetString("DownloadNewFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email copied to clipboard.
        /// </summary>
        public static string EmailCopied {
            get {
                return ResourceManager.GetString("EmailCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred.
        /// </summary>
        public static string ErrorUnknown {
            get {
                return ResourceManager.GetString("ErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send feedback.
        /// </summary>
        public static string FeedbackSend {
            get {
                return ResourceManager.GetString("FeedbackSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting files. 
        ///Please check if the device is connected and retry the action..
        /// </summary>
        public static string FileCheckError {
            get {
                return ResourceManager.GetString("FileCheckError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file already exists.
        ///Save to overwrite this file..
        /// </summary>
        public static string FileExists_Overwrite {
            get {
                return ResourceManager.GetString("FileExists_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename structure.
        /// </summary>
        public static string FilenameStructure {
            get {
                return ResourceManager.GetString("FilenameStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded.
        /// </summary>
        public static string FilesDownloadedTotal {
            get {
                return ResourceManager.GetString("FilesDownloadedTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string FilesDownloadErrorTotal {
            get {
                return ResourceManager.GetString("FilesDownloadErrorTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for files.
        /// </summary>
        public static string FileSearch {
            get {
                return ResourceManager.GetString("FileSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File search.
        /// </summary>
        public static string FileSearchState {
            get {
                return ResourceManager.GetString("FileSearchState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string FileSearchStatus_Ready {
            get {
                return ResourceManager.GetString("FileSearchStatus_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        public static string FileSearchStatus_Searching {
            get {
                return ResourceManager.GetString("FileSearchStatus_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string FileSearchStatus_Unknown {
            get {
                return ResourceManager.GetString("FileSearchStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files total.
        /// </summary>
        public static string FilesFoundTotal {
            get {
                return ResourceManager.GetString("FilesFoundTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To download.
        /// </summary>
        public static string FilesToDownload {
            get {
                return ResourceManager.GetString("FilesToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find files.
        /// </summary>
        public static string FindFiles {
            get {
                return ResourceManager.GetString("FindFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use {0} at the beginning of the name..
        /// </summary>
        public static string FirstTagError {
            get {
                return ResourceManager.GetString("FirstTagError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete folder.
        /// </summary>
        public static string FolderDelete {
            get {
                return ResourceManager.GetString("FolderDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected folder does not exist.
        /// </summary>
        public static string FolderDoesNotExist {
            get {
                return ResourceManager.GetString("FolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder structure.
        /// </summary>
        public static string FolderStructure {
            get {
                return ResourceManager.GetString("FolderStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate thumbnails.
        /// </summary>
        public static string GenerateThumbnails {
            get {
                return ResourceManager.GetString("GenerateThumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text contains invalid characters: {0}.
        /// </summary>
        public static string InvalidCharsError {
            get {
                return ResourceManager.GetString("InvalidCharsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid filename.
        /// </summary>
        public static string InvalidFilename {
            get {
                return ResourceManager.GetString("InvalidFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last backup.
        /// </summary>
        public static string LastBackup {
            get {
                return ResourceManager.GetString("LastBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string LastBackup_Never {
            get {
                return ResourceManager.GetString("LastBackup_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used libraries.
        /// </summary>
        public static string LibrariesUsed {
            get {
                return ResourceManager.GetString("LibrariesUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use a maximum of {0} tags..
        /// </summary>
        public static string MaxTagError {
            get {
                return ResourceManager.GetString("MaxTagError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media path.
        /// </summary>
        public static string MediaPath {
            get {
                return ResourceManager.GetString("MediaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder for backup.
        /// </summary>
        public static string NoBackupFolder {
            get {
                return ResourceManager.GetString("NoBackupFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder to save files.
        /// </summary>
        public static string NoDownloadFolder {
            get {
                return ResourceManager.GetString("NoDownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a filename structure.
        /// </summary>
        public static string NoFileStructure {
            get {
                return ResourceManager.GetString("NoFileStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a folder structure.
        /// </summary>
        public static string NoFolderStructure {
            get {
                return ResourceManager.GetString("NoFolderStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder for thumbnails.
        /// </summary>
        public static string NoThumbnailFolder {
            get {
                return ResourceManager.GetString("NoThumbnailFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load profile &quot;{0}&quot;. Do you want to delete it?.
        /// </summary>
        public static string Profile_Load_Error {
            get {
                return ResourceManager.GetString("Profile_Load_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete profile.
        /// </summary>
        public static string ProfileDelete {
            get {
                return ResourceManager.GetString("ProfileDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name.
        /// </summary>
        public static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating remaining time.
        /// </summary>
        public static string RemainingTime_Calculating {
            get {
                return ResourceManager.GetString("RemainingTime_Calculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        public static string RemainingTime_Days {
            get {
                return ResourceManager.GetString("RemainingTime_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string RemainingTime_Hours {
            get {
                return ResourceManager.GetString("RemainingTime_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string RemainingTime_Minutes {
            get {
                return ResourceManager.GetString("RemainingTime_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remains.
        /// </summary>
        public static string RemainingTime_Remains {
            get {
                return ResourceManager.GetString("RemainingTime_Remains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string RemainingTime_Seconds {
            get {
                return ResourceManager.GetString("RemainingTime_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart app.
        /// </summary>
        public static string RestartApp {
            get {
                return ResourceManager.GetString("RestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string ResultCanceled {
            get {
                return ResourceManager.GetString("ResultCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder.
        /// </summary>
        public static string SelectDestination {
            get {
                return ResourceManager.GetString("SelectDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a device.
        /// </summary>
        public static string SelectDevice {
            get {
                return ResourceManager.GetString("SelectDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename structure.
        /// </summary>
        public static string SelectFilename {
            get {
                return ResourceManager.GetString("SelectFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder structure.
        /// </summary>
        public static string SelectFolderStructure {
            get {
                return ResourceManager.GetString("SelectFolderStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select main folder.
        /// </summary>
        public static string SelectMainFolder {
            get {
                return ResourceManager.GetString("SelectMainFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string SettingsBackup {
            get {
                return ResourceManager.GetString("SettingsBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete downloaded files.
        /// </summary>
        public static string SettingsDeleteDownloaded {
            get {
                return ResourceManager.GetString("SettingsDeleteDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File check.
        /// </summary>
        public static string SettingsFileCheck {
            get {
                return ResourceManager.GetString("SettingsFileCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename structure.
        /// </summary>
        public static string SettingsFilenameStructure {
            get {
                return ResourceManager.GetString("SettingsFilenameStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder structure.
        /// </summary>
        public static string SettingsFolderStructure {
            get {
                return ResourceManager.GetString("SettingsFolderStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some changes will take effect after restarting the application.
        /// </summary>
        public static string SettingsInfoRestart {
            get {
                return ResourceManager.GetString("SettingsInfoRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main folder.
        /// </summary>
        public static string SettingsMainFolder {
            get {
                return ResourceManager.GetString("SettingsMainFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings.
        /// </summary>
        public static string SettingsSave {
            get {
                return ResourceManager.GetString("SettingsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path structure.
        /// </summary>
        public static string SettingsStorage {
            get {
                return ResourceManager.GetString("SettingsStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail generation.
        /// </summary>
        public static string SettingsThumbnail {
            get {
                return ResourceManager.GetString("SettingsThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show app data.
        /// </summary>
        public static string ShowAppdataFolder {
            get {
                return ResourceManager.GetString("ShowAppdataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show crash files.
        /// </summary>
        public static string ShowCrashFiles {
            get {
                return ResourceManager.GetString("ShowCrashFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show log.
        /// </summary>
        public static string ShowLog {
            get {
                return ResourceManager.GetString("ShowLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code.
        /// </summary>
        public static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string SpaceAvailable {
            get {
                return ResourceManager.GetString("SpaceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total space.
        /// </summary>
        public static string SpaceTotal {
            get {
                return ResourceManager.GetString("SpaceTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string SpaceUsed {
            get {
                return ResourceManager.GetString("SpaceUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check updates after startup.
        /// </summary>
        public static string StartupUpdateCheck {
            get {
                return ResourceManager.GetString("StartupUpdateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Tag_CustomText_Button {
            get {
                return ResourceManager.GetString("Tag_CustomText_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Tag_CustomText_VisibleText {
            get {
                return ResourceManager.GetString("Tag_CustomText_VisibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Tag_Day_Button {
            get {
                return ResourceManager.GetString("Tag_Day_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Tag_Day_VisibleText {
            get {
                return ResourceManager.GetString("Tag_Day_VisibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day long (name).
        /// </summary>
        public static string Tag_DayLong_Button {
            get {
                return ResourceManager.GetString("Tag_DayLong_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day long.
        /// </summary>
        public static string Tag_DayLong_VisibleText {
            get {
                return ResourceManager.GetString("Tag_DayLong_VisibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day short (name).
        /// </summary>
        public static string Tag_DayShort_Button {
            get {
                return ResourceManager.GetString("Tag_DayShort_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day short.
        /// </summary>
        public static string Tag_DayShort_VisibleText {
            get {
                return ResourceManager.GetString("Tag_DayShort_VisibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string Tag_DeviceManuf_Button {
            get {
                return ResourceManager.GetString("Tag_DeviceManuf_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device manufacturer.
        /// </summary>
        public static string Tag_DeviceManuf_VisibleText {
            get {
                return ResourceManager.GetString("Tag_DeviceManuf_VisibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Tag_DeviceName_Button {
            get {
                return ResourceManager.GetString("Tag_DeviceName_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device name.
        /// </summary>
        public static string Tag_DeviceName_VisibleText {
            get {
                return ResourceManager.GetString("Tag_DeviceName_VisibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string Tag_FileName_Button {
            get {
                return ResourceManager.GetString("Tag_FileName_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string Tag_FileName_VisibleText {
            get {
                return ResourceManager.GetString("Tag_FileName_VisibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Tag_Month_Button {
            get {
                return ResourceManager.GetString("Tag_Month_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Tag_Month_VisibleText {
            get {
                return ResourceManager.GetString("Tag_Month_VisibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month long (name).
        /// </summary>
        public static string Tag_MonthLong_Button {
            get {
                return ResourceManager.GetString("Tag_MonthLong_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month long.
        /// </summary>
        public static string Tag_MonthLong_VisibleText {
            get {
                return ResourceManager.GetString("Tag_MonthLong_VisibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month short (name).
        /// </summary>
        public static string Tag_MonthShort_Button {
            get {
                return ResourceManager.GetString("Tag_MonthShort_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month short.
        /// </summary>
        public static string Tag_MonthShort_VisibleText {
            get {
                return ResourceManager.GetString("Tag_MonthShort_VisibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New folder.
        /// </summary>
        public static string Tag_NewFolder_Button {
            get {
                return ResourceManager.GetString("Tag_NewFolder_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Tag_SequenceNum_Button {
            get {
                return ResourceManager.GetString("Tag_SequenceNum_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File number.
        /// </summary>
        public static string Tag_SequenceNum_VisibleText {
            get {
                return ResourceManager.GetString("Tag_SequenceNum_VisibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Tag_YearLong_Button {
            get {
                return ResourceManager.GetString("Tag_YearLong_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year long.
        /// </summary>
        public static string Tag_YearLong_VisibleText {
            get {
                return ResourceManager.GetString("Tag_YearLong_VisibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year short (YY).
        /// </summary>
        public static string Tag_YearShort_Button {
            get {
                return ResourceManager.GetString("Tag_YearShort_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year short.
        /// </summary>
        public static string Tag_YearShort_VisibleText {
            get {
                return ResourceManager.GetString("Tag_YearShort_VisibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom text.
        /// </summary>
        public static string TagCustomText {
            get {
                return ResourceManager.GetString("TagCustomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing value for {0}.
        ///Fill the value or remove the tag..
        /// </summary>
        public static string TagCustomTextMissing {
            get {
                return ResourceManager.GetString("TagCustomTextMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete tag.
        /// </summary>
        public static string TagDelete {
            get {
                return ResourceManager.GetString("TagDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string TagGroup_Custom {
            get {
                return ResourceManager.GetString("TagGroup_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string TagGroup_Date {
            get {
                return ResourceManager.GetString("TagGroup_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string TagGroup_Device {
            get {
                return ResourceManager.GetString("TagGroup_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string TagGroup_Folder {
            get {
                return ResourceManager.GetString("TagGroup_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string TagGroup_Other {
            get {
                return ResourceManager.GetString("TagGroup_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator.
        /// </summary>
        public static string TagGroup_Separator {
            get {
                return ResourceManager.GetString("TagGroup_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag language.
        /// </summary>
        public static string TagLanguage {
            get {
                return ResourceManager.GetString("TagLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use {0} after {1}..
        /// </summary>
        public static string TagPairError {
            get {
                return ResourceManager.GetString("TagPairError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longer side.
        /// </summary>
        public static string ThumbnailLongerSide {
            get {
                return ResourceManager.GetString("ThumbnailLongerSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum size.
        /// </summary>
        public static string ThumbnailMaxSize {
            get {
                return ResourceManager.GetString("ThumbnailMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shorter side.
        /// </summary>
        public static string ThumbnailShorterSide {
            get {
                return ResourceManager.GetString("ThumbnailShorterSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get information about the availability of a newer version.
        /// </summary>
        public static string Update_Error {
            get {
                return ResourceManager.GetString("Update_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version is available.
        /// </summary>
        public static string Update_NewVersionAvailable {
            get {
                return ResourceManager.GetString("Update_NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the latest version.
        /// </summary>
        public static string Update_NoNewVerison {
            get {
                return ResourceManager.GetString("Update_NoNewVerison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download manually.
        /// </summary>
        public static string UpdateDownload {
            get {
                return ResourceManager.GetString("UpdateDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string UpdateInstall {
            get {
                return ResourceManager.GetString("UpdateInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use different language for tags.
        /// </summary>
        public static string UseDifferentLanguageForTags {
            get {
                return ResourceManager.GetString("UseDifferentLanguageForTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
