//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotoApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string CardDownload {
            get {
                return ResourceManager.GetString("CardDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string CardOtherSettings {
            get {
                return ResourceManager.GetString("CardOtherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string CardProfile {
            get {
                return ResourceManager.GetString("CardProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path structure.
        /// </summary>
        public static string CardStorage {
            get {
                return ResourceManager.GetString("CardStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string CheckUpdates {
            get {
                return ResourceManager.GetString("CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark mode.
        /// </summary>
        public static string DarkMode {
            get {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string DateRangeFrom {
            get {
                return ResourceManager.GetString("DateRangeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string DateRangeTo {
            get {
                return ResourceManager.GetString("DateRangeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device name.
        /// </summary>
        public static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string DeviceState {
            get {
                return ResourceManager.GetString("DeviceState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download files by date.
        /// </summary>
        public static string DownloadDateRange {
            get {
                return ResourceManager.GetString("DownloadDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete downloaded files from device.
        /// </summary>
        public static string DownloadDeleteFile {
            get {
                return ResourceManager.GetString("DownloadDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check files.
        /// </summary>
        public static string DownloadFileCheck {
            get {
                return ResourceManager.GetString("DownloadFileCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download files.
        /// </summary>
        public static string DownloadFiles {
            get {
                return ResourceManager.GetString("DownloadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download new files since last backup.
        /// </summary>
        public static string DownloadNewFiles {
            get {
                return ResourceManager.GetString("DownloadNewFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred.
        /// </summary>
        public static string ErrorUnknown {
            get {
                return ResourceManager.GetString("ErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send feedback.
        /// </summary>
        public static string FeedbackSend {
            get {
                return ResourceManager.GetString("FeedbackSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename structure.
        /// </summary>
        public static string FilenameStructure {
            get {
                return ResourceManager.GetString("FilenameStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File search.
        /// </summary>
        public static string FileSearchState {
            get {
                return ResourceManager.GetString("FileSearchState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find files.
        /// </summary>
        public static string FindFiles {
            get {
                return ResourceManager.GetString("FindFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use {0} at the beginning of the name..
        /// </summary>
        public static string FirstTagError {
            get {
                return ResourceManager.GetString("FirstTagError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete folder.
        /// </summary>
        public static string FolderDelete {
            get {
                return ResourceManager.GetString("FolderDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder structure.
        /// </summary>
        public static string FolderStructure {
            get {
                return ResourceManager.GetString("FolderStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate thumbnails.
        /// </summary>
        public static string GenerateThumbnails {
            get {
                return ResourceManager.GetString("GenerateThumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text contains invalid characters: {0}.
        /// </summary>
        public static string InvalidCharsError {
            get {
                return ResourceManager.GetString("InvalidCharsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last backup.
        /// </summary>
        public static string LastBackup {
            get {
                return ResourceManager.GetString("LastBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use a maximum of {0} tags..
        /// </summary>
        public static string MaxTagError {
            get {
                return ResourceManager.GetString("MaxTagError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media path.
        /// </summary>
        public static string MediaPath {
            get {
                return ResourceManager.GetString("MediaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete profile.
        /// </summary>
        public static string ProfileDelete {
            get {
                return ResourceManager.GetString("ProfileDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name.
        /// </summary>
        public static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder.
        /// </summary>
        public static string SelectDestination {
            get {
                return ResourceManager.GetString("SelectDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename structure.
        /// </summary>
        public static string SelectFilename {
            get {
                return ResourceManager.GetString("SelectFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder structure.
        /// </summary>
        public static string SelectFolderStructure {
            get {
                return ResourceManager.GetString("SelectFolderStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select main folder.
        /// </summary>
        public static string SelectMainFolder {
            get {
                return ResourceManager.GetString("SelectMainFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string SettingsBackup {
            get {
                return ResourceManager.GetString("SettingsBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete downloaded files.
        /// </summary>
        public static string SettingsDeleteDownloaded {
            get {
                return ResourceManager.GetString("SettingsDeleteDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File check.
        /// </summary>
        public static string SettingsFileCheck {
            get {
                return ResourceManager.GetString("SettingsFileCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename structure.
        /// </summary>
        public static string SettingsFilenameStructure {
            get {
                return ResourceManager.GetString("SettingsFilenameStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder structure.
        /// </summary>
        public static string SettingsFolderStructure {
            get {
                return ResourceManager.GetString("SettingsFolderStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main folder.
        /// </summary>
        public static string SettingsMainFolder {
            get {
                return ResourceManager.GetString("SettingsMainFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings.
        /// </summary>
        public static string SettingsSave {
            get {
                return ResourceManager.GetString("SettingsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path structure.
        /// </summary>
        public static string SettingsStorage {
            get {
                return ResourceManager.GetString("SettingsStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail generation.
        /// </summary>
        public static string SettingsThumbnail {
            get {
                return ResourceManager.GetString("SettingsThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show files from crash.
        /// </summary>
        public static string ShowCrashFiles {
            get {
                return ResourceManager.GetString("ShowCrashFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code.
        /// </summary>
        public static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string SpaceAvailable {
            get {
                return ResourceManager.GetString("SpaceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total space.
        /// </summary>
        public static string SpaceTotal {
            get {
                return ResourceManager.GetString("SpaceTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string SpaceUsed {
            get {
                return ResourceManager.GetString("SpaceUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check updates after startup.
        /// </summary>
        public static string StartupUpdateCheck {
            get {
                return ResourceManager.GetString("StartupUpdateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom text.
        /// </summary>
        public static string TagCustomText {
            get {
                return ResourceManager.GetString("TagCustomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing value for {0}.\nFill the value or remove the tag..
        /// </summary>
        public static string TagCustomTextMissing {
            get {
                return ResourceManager.GetString("TagCustomTextMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete tag.
        /// </summary>
        public static string TagDelete {
            get {
                return ResourceManager.GetString("TagDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use {0} after {1}..
        /// </summary>
        public static string TagPairError {
            get {
                return ResourceManager.GetString("TagPairError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longer side.
        /// </summary>
        public static string ThumbnailLongerSide {
            get {
                return ResourceManager.GetString("ThumbnailLongerSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum size.
        /// </summary>
        public static string ThumbnailMaxSize {
            get {
                return ResourceManager.GetString("ThumbnailMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shorter side.
        /// </summary>
        public static string ThumbnailShorterSide {
            get {
                return ResourceManager.GetString("ThumbnailShorterSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
