//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_cs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_cs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotoApp.Properties.Resources.cs", typeof(Resources_cs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O aplikaci.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verze aplikace.
        /// </summary>
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Záloha.
        /// </summary>
        public static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušit.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota nemůže být 0.
        /// </summary>
        public static string CannotBeZero {
            get {
                return ResourceManager.GetString("CannotBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stažení.
        /// </summary>
        public static string CardDownload {
            get {
                return ResourceManager.GetString("CardDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostatní.
        /// </summary>
        public static string CardOtherSettings {
            get {
                return ResourceManager.GetString("CardOtherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string CardProfile {
            get {
                return ResourceManager.GetString("CardProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struktura uložení.
        /// </summary>
        public static string CardStorage {
            get {
                return ResourceManager.GetString("CardStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co je nového?.
        /// </summary>
        public static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravy.
        /// </summary>
        public static string Changelog_Fixes {
            get {
                return ResourceManager.GetString("Changelog_Fixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oprava překladu
        ///oprava UI
        ///automatické mazání starých log souborů
        ///kontrola profilu před načtením
        ///může běžet jen jedno okno aplikace
        ///oprava pádu aplikace při instalaci aktualizace.
        /// </summary>
        public static string Changelog_Fixes_List {
            get {
                return ResourceManager.GetString("Changelog_Fixes_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novinky.
        /// </summary>
        public static string Changelog_NewFeatures {
            get {
                return ResourceManager.GetString("Changelog_NewFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to využití vložených náhledů pro generování zmenšených fotografií (až 2x rychlejší generování, používá až 6x méně paměti)
        ///možnost zvolit jiný jazyk pro značky (název dnů a měsíců)
        ///zobrazení změn po aktualizaci
        ///možnost zobrazení změn a dat aplikace z dialogu O aplikaci
        ///možnost aktualizovat nastavení profilu použitím možnosti Uložit jako
        ///první připojené zařízení se automaticky vybere.
        /// </summary>
        public static string Changelog_NewFeatures_List {
            get {
                return ResourceManager.GetString("Changelog_NewFeatures_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zkontolovat aktualizace.
        /// </summary>
        public static string CheckUpdates {
            get {
                return ResourceManager.GetString("CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopírovat.
        /// </summary>
        public static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tmavý režim.
        /// </summary>
        public static string DarkMode {
            get {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počáteční datum nemůže být větší než koncové.
        /// </summary>
        public static string DateRange_StartGreater {
            get {
                return ResourceManager.GetString("DateRange_StartGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Od.
        /// </summary>
        public static string DateRangeFrom {
            get {
                return ResourceManager.GetString("DateRangeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string DateRangeTo {
            get {
                return ResourceManager.GetString("DateRangeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přejete si smazat profil [{0}]?.
        /// </summary>
        public static string DeleteProfilePrompt {
            get {
                return ResourceManager.GetString("DeleteProfilePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopíruji soubory.
        /// </summary>
        public static string DeviceCopyingFiles {
            get {
                return ResourceManager.GetString("DeviceCopyingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mazání souboru {0}.
        /// </summary>
        public static string DeviceDeletingFile {
            get {
                return ResourceManager.GetString("DeviceDeletingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mazání stažených souborů ze zařízení.
        /// </summary>
        public static string DeviceDeletingFilesTask {
            get {
                return ResourceManager.GetString("DeviceDeletingFilesTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazáno {0}/{1} souborů.
        /// </summary>
        public static string DeviceDeletingProgress {
            get {
                return ResourceManager.GetString("DeviceDeletingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stahuji {0}.
        /// </summary>
        public static string DeviceDownloadingFile {
            get {
                return ResourceManager.GetString("DeviceDownloadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrování souborů podle data.
        /// </summary>
        public static string DeviceFileFilterDate {
            get {
                return ResourceManager.GetString("DeviceFileFilterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpracováno {0}/{1} souborů.
        /// </summary>
        public static string DeviceFilesDoneCount {
            get {
                return ResourceManager.GetString("DeviceFilesDoneCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nalezeno {0} souborů.
        /// </summary>
        public static string DeviceFilesFound {
            get {
                return ResourceManager.GetString("DeviceFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generuji náhled {0}.
        /// </summary>
        public static string DeviceGeneratingThumbnail {
            get {
                return ResourceManager.GetString("DeviceGeneratingThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název zařízení.
        /// </summary>
        public static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte název zařízení.
        /// </summary>
        public static string DeviceNameEmpty {
            get {
                return ResourceManager.GetString("DeviceNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Třídím soubor {0}.
        /// </summary>
        public static string DeviceSortingFile {
            get {
                return ResourceManager.GetString("DeviceSortingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stav.
        /// </summary>
        public static string DeviceState {
            get {
                return ResourceManager.GetString("DeviceState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nelze se připojit.
        /// </summary>
        public static string DeviceStatus_CannotConnect {
            get {
                return ResourceManager.GetString("DeviceStatus_CannotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Připraveno.
        /// </summary>
        public static string DeviceStatus_Ready {
            get {
                return ResourceManager.GetString("DeviceStatus_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neznámý.
        /// </summary>
        public static string DeviceStatus_Unknown {
            get {
                return ResourceManager.GetString("DeviceStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotovo.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stažení souborů dle data.
        /// </summary>
        public static string DownloadDateRange {
            get {
                return ResourceManager.GetString("DownloadDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat stažené soubory ze zařízení.
        /// </summary>
        public static string DownloadDeleteFile {
            get {
                return ResourceManager.GetString("DownloadDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrola souborů.
        /// </summary>
        public static string DownloadFileCheck {
            get {
                return ResourceManager.GetString("DownloadFileCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stáhnout soubory.
        /// </summary>
        public static string DownloadFiles {
            get {
                return ResourceManager.GetString("DownloadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stažení nových souborů od poslední zálohy.
        /// </summary>
        public static string DownloadNewFiles {
            get {
                return ResourceManager.GetString("DownloadNewFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email zkopírován do schránky.
        /// </summary>
        public static string EmailCopied {
            get {
                return ResourceManager.GetString("EmailCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyskytla se neznámá chyba.
        /// </summary>
        public static string ErrorUnknown {
            get {
                return ResourceManager.GetString("ErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpětná vazba.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odeslat zpětnou vazbu.
        /// </summary>
        public static string FeedbackSend {
            get {
                return ResourceManager.GetString("FeedbackSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Při získávání souborů došlo k chybě. 
        ///Prosím zkontrolujte, zda je zařízení připojené a akci zopakujte..
        /// </summary>
        public static string FileCheckError {
            get {
                return ResourceManager.GetString("FileCheckError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor již existuje.
        ///Uložením tento soubor přepíšete..
        /// </summary>
        public static string FileExists_Overwrite {
            get {
                return ResourceManager.GetString("FileExists_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název souboru.
        /// </summary>
        public static string FilenameStructure {
            get {
                return ResourceManager.GetString("FilenameStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staženo.
        /// </summary>
        public static string FilesDownloadedTotal {
            get {
                return ResourceManager.GetString("FilesDownloadedTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyby.
        /// </summary>
        public static string FilesDownloadErrorTotal {
            get {
                return ResourceManager.GetString("FilesDownloadErrorTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hledám soubory.
        /// </summary>
        public static string FileSearch {
            get {
                return ResourceManager.GetString("FileSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyhledávání souborů.
        /// </summary>
        public static string FileSearchState {
            get {
                return ResourceManager.GetString("FileSearchState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokončeno.
        /// </summary>
        public static string FileSearchStatus_Ready {
            get {
                return ResourceManager.GetString("FileSearchStatus_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probíhá.
        /// </summary>
        public static string FileSearchStatus_Searching {
            get {
                return ResourceManager.GetString("FileSearchStatus_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neznámý.
        /// </summary>
        public static string FileSearchStatus_Unknown {
            get {
                return ResourceManager.GetString("FileSearchStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Souborů celkem.
        /// </summary>
        public static string FilesFoundTotal {
            get {
                return ResourceManager.GetString("FilesFoundTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ke stažení.
        /// </summary>
        public static string FilesToDownload {
            get {
                return ResourceManager.GetString("FilesToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyhledat soubory.
        /// </summary>
        public static string FindFiles {
            get {
                return ResourceManager.GetString("FindFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nelze použít {0} na začátku názvu..
        /// </summary>
        public static string FirstTagError {
            get {
                return ResourceManager.GetString("FirstTagError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat složku.
        /// </summary>
        public static string FolderDelete {
            get {
                return ResourceManager.GetString("FolderDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvolená složka neexistuje.
        /// </summary>
        public static string FolderDoesNotExist {
            get {
                return ResourceManager.GetString("FolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pojmenování složek.
        /// </summary>
        public static string FolderStructure {
            get {
                return ResourceManager.GetString("FolderStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generovat náhledy.
        /// </summary>
        public static string GenerateThumbnails {
            get {
                return ResourceManager.GetString("GenerateThumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text obsahuje neplatné znaky: {0}.
        /// </summary>
        public static string InvalidCharsError {
            get {
                return ResourceManager.GetString("InvalidCharsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neplatný název souboru.
        /// </summary>
        public static string InvalidFilename {
            get {
                return ResourceManager.GetString("InvalidFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jazyk.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poslední záloha.
        /// </summary>
        public static string LastBackup {
            get {
                return ResourceManager.GetString("LastBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nikdy.
        /// </summary>
        public static string LastBackup_Never {
            get {
                return ResourceManager.GetString("LastBackup_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Použité knihovny.
        /// </summary>
        public static string LibrariesUsed {
            get {
                return ResourceManager.GetString("LibrariesUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výrobce.
        /// </summary>
        public static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lze použít maximálně {0} značek..
        /// </summary>
        public static string MaxTagError {
            get {
                return ResourceManager.GetString("MaxTagError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umístění médií.
        /// </summary>
        public static string MediaPath {
            get {
                return ResourceManager.GetString("MediaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvlote složku pro zálohu.
        /// </summary>
        public static string NoBackupFolder {
            get {
                return ResourceManager.GetString("NoBackupFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvolte složku pro uložení souborů.
        /// </summary>
        public static string NoDownloadFolder {
            get {
                return ResourceManager.GetString("NoDownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvlote strukturu pro název souboru.
        /// </summary>
        public static string NoFileStructure {
            get {
                return ResourceManager.GetString("NoFileStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvlote strukturu složek pro uložení.
        /// </summary>
        public static string NoFolderStructure {
            get {
                return ResourceManager.GetString("NoFolderStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvolte složku pro náhledy.
        /// </summary>
        public static string NoThumbnailFolder {
            get {
                return ResourceManager.GetString("NoThumbnailFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil &quot;{0}&quot; nelze načíst. Chcete jej smazat?.
        /// </summary>
        public static string Profile_Load_Error {
            get {
                return ResourceManager.GetString("Profile_Load_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat profil.
        /// </summary>
        public static string ProfileDelete {
            get {
                return ResourceManager.GetString("ProfileDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název profilu.
        /// </summary>
        public static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obnovit.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počítám zbývající čas.
        /// </summary>
        public static string RemainingTime_Calculating {
            get {
                return ResourceManager.GetString("RemainingTime_Calculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        public static string RemainingTime_Days {
            get {
                return ResourceManager.GetString("RemainingTime_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string RemainingTime_Hours {
            get {
                return ResourceManager.GetString("RemainingTime_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string RemainingTime_Minutes {
            get {
                return ResourceManager.GetString("RemainingTime_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zbývá.
        /// </summary>
        public static string RemainingTime_Remains {
            get {
                return ResourceManager.GetString("RemainingTime_Remains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string RemainingTime_Seconds {
            get {
                return ResourceManager.GetString("RemainingTime_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restartovat aplikaci.
        /// </summary>
        public static string RestartApp {
            get {
                return ResourceManager.GetString("RestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušeno.
        /// </summary>
        public static string ResultCanceled {
            get {
                return ResourceManager.GetString("ResultCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit jako.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vybrat umístění.
        /// </summary>
        public static string SelectDestination {
            get {
                return ResourceManager.GetString("SelectDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvolte zařízení.
        /// </summary>
        public static string SelectDevice {
            get {
                return ResourceManager.GetString("SelectDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název souboru.
        /// </summary>
        public static string SelectFilename {
            get {
                return ResourceManager.GetString("SelectFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pojmenování složek.
        /// </summary>
        public static string SelectFolderStructure {
            get {
                return ResourceManager.GetString("SelectFolderStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vybrat hlavní složku.
        /// </summary>
        public static string SelectMainFolder {
            get {
                return ResourceManager.GetString("SelectMainFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavení.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Záloha.
        /// </summary>
        public static string SettingsBackup {
            get {
                return ResourceManager.GetString("SettingsBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat stažené soubory.
        /// </summary>
        public static string SettingsDeleteDownloaded {
            get {
                return ResourceManager.GetString("SettingsDeleteDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrola souborů.
        /// </summary>
        public static string SettingsFileCheck {
            get {
                return ResourceManager.GetString("SettingsFileCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název souboru.
        /// </summary>
        public static string SettingsFilenameStructure {
            get {
                return ResourceManager.GetString("SettingsFilenameStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pojmenování složek.
        /// </summary>
        public static string SettingsFolderStructure {
            get {
                return ResourceManager.GetString("SettingsFolderStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Některé změny se projeví po restartu aplikace.
        /// </summary>
        public static string SettingsInfoRestart {
            get {
                return ResourceManager.GetString("SettingsInfoRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hlavní složka.
        /// </summary>
        public static string SettingsMainFolder {
            get {
                return ResourceManager.GetString("SettingsMainFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit nastavení.
        /// </summary>
        public static string SettingsSave {
            get {
                return ResourceManager.GetString("SettingsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struktura uložení.
        /// </summary>
        public static string SettingsStorage {
            get {
                return ResourceManager.GetString("SettingsStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generování náhledů.
        /// </summary>
        public static string SettingsThumbnail {
            get {
                return ResourceManager.GetString("SettingsThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobrazit.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobrazit data aplikace.
        /// </summary>
        public static string ShowAppdataFolder {
            get {
                return ResourceManager.GetString("ShowAppdataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobrazit soubory z pádu aplikace.
        /// </summary>
        public static string ShowCrashFiles {
            get {
                return ResourceManager.GetString("ShowCrashFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobrazit log.
        /// </summary>
        public static string ShowLog {
            get {
                return ResourceManager.GetString("ShowLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdrojový kód.
        /// </summary>
        public static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostupné.
        /// </summary>
        public static string SpaceAvailable {
            get {
                return ResourceManager.GetString("SpaceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celkové úložiště.
        /// </summary>
        public static string SpaceTotal {
            get {
                return ResourceManager.GetString("SpaceTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Využité.
        /// </summary>
        public static string SpaceUsed {
            get {
                return ResourceManager.GetString("SpaceUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrola aktualizací po spuštění.
        /// </summary>
        public static string StartupUpdateCheck {
            get {
                return ResourceManager.GetString("StartupUpdateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Tag_CustomText_Button {
            get {
                return ResourceManager.GetString("Tag_CustomText_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Tag_CustomText_VisibleText {
            get {
                return ResourceManager.GetString("Tag_CustomText_VisibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den.
        /// </summary>
        public static string Tag_Day_Button {
            get {
                return ResourceManager.GetString("Tag_Day_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den.
        /// </summary>
        public static string Tag_Day_VisibleText {
            get {
                return ResourceManager.GetString("Tag_Day_VisibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den dlouze (název).
        /// </summary>
        public static string Tag_DayLong_Button {
            get {
                return ResourceManager.GetString("Tag_DayLong_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den dlouze.
        /// </summary>
        public static string Tag_DayLong_VisibleText {
            get {
                return ResourceManager.GetString("Tag_DayLong_VisibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den krátce (název).
        /// </summary>
        public static string Tag_DayShort_Button {
            get {
                return ResourceManager.GetString("Tag_DayShort_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den krátce.
        /// </summary>
        public static string Tag_DayShort_VisibleText {
            get {
                return ResourceManager.GetString("Tag_DayShort_VisibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výrobce.
        /// </summary>
        public static string Tag_DeviceManuf_Button {
            get {
                return ResourceManager.GetString("Tag_DeviceManuf_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výrobce zařízení.
        /// </summary>
        public static string Tag_DeviceManuf_VisibleText {
            get {
                return ResourceManager.GetString("Tag_DeviceManuf_VisibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        public static string Tag_DeviceName_Button {
            get {
                return ResourceManager.GetString("Tag_DeviceName_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název zařízení.
        /// </summary>
        public static string Tag_DeviceName_VisibleText {
            get {
                return ResourceManager.GetString("Tag_DeviceName_VisibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název souboru.
        /// </summary>
        public static string Tag_FileName_Button {
            get {
                return ResourceManager.GetString("Tag_FileName_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název souboru.
        /// </summary>
        public static string Tag_FileName_VisibleText {
            get {
                return ResourceManager.GetString("Tag_FileName_VisibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Měsíc.
        /// </summary>
        public static string Tag_Month_Button {
            get {
                return ResourceManager.GetString("Tag_Month_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Měsíc.
        /// </summary>
        public static string Tag_Month_VisibleText {
            get {
                return ResourceManager.GetString("Tag_Month_VisibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Měsíc dlouze (název).
        /// </summary>
        public static string Tag_MonthLong_Button {
            get {
                return ResourceManager.GetString("Tag_MonthLong_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Měsíc dlouze.
        /// </summary>
        public static string Tag_MonthLong_VisibleText {
            get {
                return ResourceManager.GetString("Tag_MonthLong_VisibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Měsíc krátce (název).
        /// </summary>
        public static string Tag_MonthShort_Button {
            get {
                return ResourceManager.GetString("Tag_MonthShort_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Měsíc krátce.
        /// </summary>
        public static string Tag_MonthShort_VisibleText {
            get {
                return ResourceManager.GetString("Tag_MonthShort_VisibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová složka.
        /// </summary>
        public static string Tag_NewFolder_Button {
            get {
                return ResourceManager.GetString("Tag_NewFolder_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo.
        /// </summary>
        public static string Tag_SequenceNum_Button {
            get {
                return ResourceManager.GetString("Tag_SequenceNum_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo souboru.
        /// </summary>
        public static string Tag_SequenceNum_VisibleText {
            get {
                return ResourceManager.GetString("Tag_SequenceNum_VisibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rok.
        /// </summary>
        public static string Tag_YearLong_Button {
            get {
                return ResourceManager.GetString("Tag_YearLong_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rok dlouze.
        /// </summary>
        public static string Tag_YearLong_VisibleText {
            get {
                return ResourceManager.GetString("Tag_YearLong_VisibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rok krátce (YY).
        /// </summary>
        public static string Tag_YearShort_Button {
            get {
                return ResourceManager.GetString("Tag_YearShort_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rok krátce.
        /// </summary>
        public static string Tag_YearShort_VisibleText {
            get {
                return ResourceManager.GetString("Tag_YearShort_VisibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlastní text.
        /// </summary>
        public static string TagCustomText {
            get {
                return ResourceManager.GetString("TagCustomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chybí hodnota pro {0}.
        ///Doplňte tuto hodnotu nebo značku odstraňte..
        /// </summary>
        public static string TagCustomTextMissing {
            get {
                return ResourceManager.GetString("TagCustomTextMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat značku.
        /// </summary>
        public static string TagDelete {
            get {
                return ResourceManager.GetString("TagDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlastní.
        /// </summary>
        public static string TagGroup_Custom {
            get {
                return ResourceManager.GetString("TagGroup_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string TagGroup_Date {
            get {
                return ResourceManager.GetString("TagGroup_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zařízení.
        /// </summary>
        public static string TagGroup_Device {
            get {
                return ResourceManager.GetString("TagGroup_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Složka.
        /// </summary>
        public static string TagGroup_Folder {
            get {
                return ResourceManager.GetString("TagGroup_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostatní.
        /// </summary>
        public static string TagGroup_Other {
            get {
                return ResourceManager.GetString("TagGroup_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oddělovač.
        /// </summary>
        public static string TagGroup_Separator {
            get {
                return ResourceManager.GetString("TagGroup_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jazyk pro značky.
        /// </summary>
        public static string TagLanguage {
            get {
                return ResourceManager.GetString("TagLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nelze použít {0} po {1}..
        /// </summary>
        public static string TagPairError {
            get {
                return ResourceManager.GetString("TagPairError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Značky.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delší strana.
        /// </summary>
        public static string ThumbnailLongerSide {
            get {
                return ResourceManager.GetString("ThumbnailLongerSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximální velikost.
        /// </summary>
        public static string ThumbnailMaxSize {
            get {
                return ResourceManager.GetString("ThumbnailMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kratší strana.
        /// </summary>
        public static string ThumbnailShorterSide {
            get {
                return ResourceManager.GetString("ThumbnailShorterSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualizace.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nebylo možné získat informace o dostupnosti novější verze.
        /// </summary>
        public static string Update_Error {
            get {
                return ResourceManager.GetString("Update_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je dostupná novější verze programu.
        /// </summary>
        public static string Update_NewVersionAvailable {
            get {
                return ResourceManager.GetString("Update_NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máte nejnovější verzi programu.
        /// </summary>
        public static string Update_NoNewVerison {
            get {
                return ResourceManager.GetString("Update_NoNewVerison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stáhnout ručně.
        /// </summary>
        public static string UpdateDownload {
            get {
                return ResourceManager.GetString("UpdateDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nainstalovat.
        /// </summary>
        public static string UpdateInstall {
            get {
                return ResourceManager.GetString("UpdateInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Použít jiný jazyk pro značky.
        /// </summary>
        public static string UseDifferentLanguageForTags {
            get {
                return ResourceManager.GetString("UseDifferentLanguageForTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
