//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TagCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TagCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotoApp.Properties.TagCodes", typeof(TagCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STR.
        /// </summary>
        public static string CustomText {
            get {
                return ResourceManager.GetString("CustomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DD.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDDD.
        /// </summary>
        public static string DayLong {
            get {
                return ResourceManager.GetString("DayLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDD.
        /// </summary>
        public static string DayShort {
            get {
                return ResourceManager.GetString("DayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DM.
        /// </summary>
        public static string DeviceManuf {
            get {
                return ResourceManager.GetString("DeviceManuf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DN.
        /// </summary>
        public static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FN.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HYP.
        /// </summary>
        public static string Hyphen {
            get {
                return ResourceManager.GetString("Hyphen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMMM.
        /// </summary>
        public static string MonthLong {
            get {
                return ResourceManager.GetString("MonthLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMM.
        /// </summary>
        public static string MonthShort {
            get {
                return ResourceManager.GetString("MonthShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NF.
        /// </summary>
        public static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SN.
        /// </summary>
        public static string SequenceNum {
            get {
                return ResourceManager.GetString("SequenceNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNDS.
        /// </summary>
        public static string Underscore {
            get {
                return ResourceManager.GetString("Underscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YY.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YYYY.
        /// </summary>
        public static string YearLong {
            get {
                return ResourceManager.GetString("YearLong", resourceCulture);
            }
        }
    }
}
